# Generated by Django 6.0.4 on 2026-05-01 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(blank=True, null=True)),
                ('ciphertext', models.TextField()),
                ('encrypted_key', models.TextField()),
                ('nonce', models.CharField(max_length=24)),
                ('auth_tag', models.CharField(max_length=24)),
                ('signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, db_column='recipient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'indexes': [models.Index(fields=['sender'], name='idx_messages_sender'), models.Index(fields=['recipient'], name='idx_messages_recipient')],
            },
        ),
    ]
