# Generated by Django 6.0.4 on 2026-05-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_module', '0002_group_groupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
