# Generated by Django 6.0.4 on 2026-05-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_module', '0003_alter_groupmember_id'),
        ('crypto_module', '0003_group_key_message_encrypted_key_blank'),
    ]

    operations = [
    ]
