# Generated by Django 6.0.4 on 2026-05-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_module', '0004_merge_20260507_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_key',
        ),
    ]
