# Generated by Django 6.0.4 on 2026-05-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(unique=True)),
                ("timestamp", models.DateTimeField()),
                ("sender_id", models.UUIDField(blank=True, null=True)),
                ("recipient_id", models.UUIDField(blank=True, null=True)),
                ("message_hash", models.CharField(max_length=64)),
                ("previous_hash", models.CharField(max_length=64)),
                ("nonce", models.IntegerField(default=0)),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "blockchain",
                "ordering": ["index"],
            },
        ),
    ]
